# Use phantom JS rpi image which is on top of node rpi
FROM ollihoo/phantomjs-docker-rpi

RUN echo node -v

# Create app directory
RUN mkdir -p /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
COPY . /usr/src/app/

WORKDIR /usr/src/app
RUN npm install -g yarn && yarn install

EXPOSE 8080
CMD ["npm", "start"]
