# Use phantom JS rpi image which is on top of node rpi
FROM registry:5000/phantomjs-docker-rpi

# Create app directory
RUN mkdir -p /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
COPY . /usr/src/app/

WORKDIR /usr/src/app
RUN yarn install

EXPOSE 8080
CMD ["npm", "start"]
